### ISSUE TITLE
LRU Cache Implementation

### ISSUE THREAD

**Issue by pratikj697** [Dipanshu089/Hacktoberfest-2024#29]
Design and implement a data structure for a Least Recently Used (LRU) cache. The cache should support the following operations efficiently:

1. get(key):
a)Retrieve the value associated with the given key.
b)If the key is not present in the cache, return -1.
2. put(key, value):
a)Insert the key-value pair into the cache.
b)If the number of keys exceeds the capacity of the cache, remove the least recently used key before inserting the new one.
c)The cache should operate within a fixed capacity and remove the least recently used element when the cache size exceeds its capacity.

Constraints:
The get and put operations must run in O(1) time.
All keys and values are positive integers.

Can you please assign these Task to me under HacktoberFest 2024.

**Comment by Dipanshu089** [comment]
you need to make an pull request not an issue in order to make it count for successful PR for hacktoberfest 2024
